language: python

python:
  - "3.6"

services:
  - postgresql

install:
  - pip install -r requirements.txt

before_script:
  - "psql -c 'create database d44f6hfmbs0tfq;' -U postgres"


script:
  - pytest tests --cov=api 

after_success:
  - coveralls